-- ============================================================
-- Digi+wo Math Hub — Game Session Migration
-- Run this AFTER database.sql has been executed
-- ============================================================

USE Digitwo_db;

-- Game sessions: tracks each play session with server-side generated questions
CREATE TABLE IF NOT EXISTS game_sessions (
    id              INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id         INT UNSIGNED NOT NULL,
    grade_id        TINYINT UNSIGNED NOT NULL,
    topic_id        SMALLINT UNSIGNED NOT NULL,
    game_type_id    VARCHAR(10) NOT NULL,
    total_questions TINYINT UNSIGNED NOT NULL DEFAULT 15,
    correct_count   TINYINT UNSIGNED NOT NULL DEFAULT 0,
    score_pct       TINYINT UNSIGNED,
    stars           TINYINT UNSIGNED,
    status          ENUM('active','completed','abandoned') DEFAULT 'active',
    started_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP NULL,
    FOREIGN KEY (user_id)      REFERENCES users(id)      ON DELETE CASCADE,
    FOREIGN KEY (grade_id)     REFERENCES grades(id),
    FOREIGN KEY (topic_id)     REFERENCES topics(id),
    FOREIGN KEY (game_type_id) REFERENCES game_types(id),
    INDEX idx_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Individual questions generated by the server for each game session
CREATE TABLE IF NOT EXISTS game_session_questions (
    id              INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    session_id      INT UNSIGNED NOT NULL,
    question_order  TINYINT UNSIGNED NOT NULL,
    prompt          VARCHAR(500) NOT NULL,
    correct_answer  VARCHAR(100) NOT NULL,    -- stored server-side only
    options         JSON NOT NULL,             -- array of choice values
    user_answer     VARCHAR(100),
    is_correct      BOOLEAN,
    answered_at     TIMESTAMP NULL,
    FOREIGN KEY (session_id) REFERENCES game_sessions(id) ON DELETE CASCADE,
    UNIQUE KEY uq_session_question (session_id, question_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
